version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-minor:
        dependency-type: development
        update-types: [minor, patch]
      prod-minor:
        dependency-type: production
        update-types: [minor, patch]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
    commit-message:
      prefix: ci
