import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import importX from 'eslint-plugin-import-x';
import stylex from '@stylexjs/eslint-plugin';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'playwright-report',
      'test-results',
      // Generated by playwright-bdd from e2e/features/*.feature; gitignored,
      // not source, and regenerated on every `npm run e2e`.
      'e2e/**/*.feature.spec.js',
      'docs/design',
      '.claude/skills',
      // Gitignored scratch space for design-tool handoffs (see .gitignore);
      // contains a vendored, minified bundle that is not this project's
      // source and was never meant to be linted.
      'tmp',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    // typescript-eslint's base config sets the TS parser with no `files`
    // restriction, so its type-checked rules reach JavaScript too and then
    // crash on it: they call getParserServices, and no parserOptions project
    // covers a `.js` file. The failure is an ESLint stack trace rather than a
    // lint error, so it takes down `npm run lint` and the pre-commit hook
    // together.
    //
    // This was scoped to the two root config files by name, to stop a future
    // `.js` file silently losing typed linting. That reasoning assumed the
    // alternative was silence; it is a crash. It also assumed typed linting
    // was available to lose, and no tsconfig here sets `allowJs`, so no
    // JavaScript file is in a project and none of it was ever type-checked.
    // The exemption now says so. Narrow it back to a named list if `allowJs`
    // is ever enabled, because then the silence would be real.
    files: ['**/*.{js,cjs,mjs}'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
      'import-x': importX,
      '@stylexjs': stylex,
    },
    // import-x resolves relative imports before `no-restricted-paths` and
    // `no-cycle` can check them, and its bundled resolver only tries
    // .mjs/.cjs/.js/.json/.node extensions. Every extensionless `.ts`/`.tsx`
    // import in this codebase (e.g. `../color/contrast`) then fails to
    // resolve, both rules silently skip it, and lint stays green with no
    // warning that it checked nothing. eslint-import-resolver-node is
    // installed for exactly this: naming it here makes the resolver also
    // try TypeScript's extensions.
    settings: {
      'import-x/resolver': {
        node: {
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        },
      },
    },
    rules: {
      // eslint-plugin-react-hooks 7.x renamed its flat-config exports. If
      // `configs.recommended.rules` is undefined at runtime, check what the
      // installed version exports — `configs['recommended-latest']` and
      // `configs.flat.recommended` are the other spellings in circulation —
      // rather than dropping the spread and losing the rules silently.
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
      'react-refresh/only-export-components': 'warn',

      // These two are the rules that would have caught the prototype's
      // suggestion block: a bare <div> with pointer handlers, no role and no
      // tabIndex — the app's primary interaction, unreachable by keyboard.
      'jsx-a11y/no-static-element-interactions': 'error',
      'jsx-a11y/interactive-supports-focus': 'error',

      // StyleX has no flat-config preset; rules are wired by hand.
      '@stylexjs/valid-styles': 'error',
      '@stylexjs/enforce-extension': 'error',
      '@stylexjs/no-unused': 'error',

      // Layering. model, color and storage may each only import themselves
      // and model. session may reach color, because select.ts is the join
      // between the session and the engine. ui may not reach session, which
      // is what keeps the components presentational. Nothing outside app
      // imports app, enforced together with the override block below. A zone
      // only enforces once its target directory exists, so session and
      // features stay unverified until the tasks that create them.
      'import-x/no-restricted-paths': [
        'error',
        {
          zones: [
            { target: './src/model', from: './src', except: ['./model'] },
            { target: './src/color', from: './src', except: ['./model', './color'] },
            { target: './src/storage', from: './src', except: ['./model', './storage'] },
            { target: './src/session', from: './src', except: ['./model', './color', './session'] },
            {
              target: './src/ui',
              from: './src',
              except: ['./model', './color', './styles', './ui'],
            },
            {
              target: './src/features',
              from: './src',
              except: [
                './model',
                './color',
                './storage',
                './session',
                './styles',
                './ui',
                './features',
              ],
            },
            { target: './src', from: './src/app' },
          ],
        },
      ],
      'import-x/no-cycle': 'error',
    },
  },
  {
    // This block must stay after the block defining `import-x/no-restricted-paths`:
    // flat config applies later blocks over earlier ones, so reordering these two
    // would silently turn the rule back on for app with no warning.
    // The zone above targets all of `./src`, including app's own files, so
    // it would otherwise flag app importing from itself. Turning the rule
    // off here instead of adding an `except` path exempts app without
    // relying on a directory list that future top-level folders (styles
    // today, session/ui/features later) could silently fall outside of.
    // This costs nothing: zones 1-3 target model, color and storage
    // specifically, so they never matched app's files either way.
    files: ['src/app/**'],
    rules: {
      'import-x/no-restricted-paths': 'off',
    },
  },
  {
    // The session's value is that its transitions are a plain data transform:
    // exhaustively testable, and readable without a renderer in your head.
    // Its React bindings sit beside it so features can reach them, so the
    // boundary that used to be a directory is this rule instead.
    files: ['src/session/reducer.ts', 'src/session/select.ts', 'src/session/types.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { paths: [{ name: 'react', message: 'The session reducer stays free of React.' }] },
      ],
    },
  },
  prettier,
);
